spring:
  application:
    name: heartime

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://heartime-db.clgayokw8l5y.ap-northeast-2.rds.amazonaws.com:3306/heartime-db?sslMode=PREFERRED&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: master
    password: tmdwns501!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: true

jwt:
  secret: C+paGTDITAStRisGeK1oBJ+D8yy7riLNwcDJ6TAeV8k=
  expiration: 7200000  # 2시간

server:
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
    groups-order: desc
    tags-sorter: alpha
    operationsSorter: method
  api-docs:
    path: /api/v3/api-docs
  paths-to-match:
    - /api/**



